version: '3.5'

services:
  lumen:
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    build: .
    command: php -S lumen:8000 -t public
    restart: always
    depends_on:
      - db_mysql
      - db_mssql
  db_mysql:
    image: mysql:8.0
    restart: always
    ports: 
      - 3306:3306 #exposing the database to the host localhost
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/mysql_data:/var/lib/mysql

  db_mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: 178@444@6213
      MSSQL_PID: Developer
    ports:
      - 1433:1433
    volumes:
      - ./database/mssql_data:/var/opt/mssql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
    - 8080:80
    environment:
    - PMA_ARBITRARY=1

volumes:
  mysql-data:
  